name: Build Linux AMD64

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set environment variables
        run: |
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "GOOS=linux" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v0.0.0-${GITHUB_SHA::8}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "ARCH_NAME=x86_64" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "GOARCH=${GOARCH}"
          echo "GOOS=${GOOS}"
          echo "VERSION=${VERSION}"

      - name: Build for Linux AMD64
        run: |
          export GOARCH=${GOARCH}
          export GOOS=${GOOS}
          make build-linux-with-shared-library \
          && cd ./build \
          && mv libmovevm.so libmovevm.${ARCH_NAME}.so \
          && mv libcompiler.so libcompiler.${ARCH_NAME}.so \
          && tar -czvf minimove_${VERSION}_Linux_${ARCH_NAME}.tar.gz minitiad libmovevm.${ARCH_NAME}.so libcompiler.${ARCH_NAME}.so \
          && mv ./minimove_"$VERSION"_Linux_"$ARCH_NAME".tar.gz $GITHUB_WORKSPACE/ \
          && rm -rf libmovevm.${ARCH_NAME}.so libcompiler.${ARCH_NAME}.so ./minitiad

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minimove_linux_amd64.tar.gz
          path: minimove_${{ env.VERSION }}_Linux_${{ env.ARCH_NAME }}.tar.gz
        env:
          VERSION: ${{ env.VERSION }}
          ARCH_NAME: ${{ env.ARCH_NAME }}
