name: Build and Upload to releases

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux-amd64:
    uses: ./.github/workflows/build-linux-amd64.yml

  build-linux-arm64:
    uses: ./.github/workflows/build-linux-arm64.yml

  build-darwin-amd64:
    uses: ./.github/workflows/build-darwin-amd64.yml

  build-darwin-arm64:
    uses: ./.github/workflows/build-darwin-arm64.yml

  release:
    name: Release build artifacts
    needs:
      - build-linux-amd64
      - build-linux-arm64
      - build-darwin-amd64
      - build-darwin-arm64
    runs-on: ubuntu-22.04
    steps:
      - name: Download linux amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: minimove_linux_amd64.tar.gz

      - name: Download linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: minimove_linux_arm64.tar.gz

      - name: Download darwin amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: minimove_darwin_amd64.tar.gz

      - name: Download darwin arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: minimove_darwin_arm64.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            minimove_linux_amd64.tar.gz
            minimove_linux_arm64.tar.gz
            minimove_darwin_amd64.tar.gz
            minimove_darwin_arm64.tar.gz
